In [2]:
# Import necessary libraries
import pandas as pd
import numpy as np

In [3]:
# Load dataset
df = pd.read_csv("../data/raw/car_prices.csv")

# Show first 5 rows
df.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [4]:
# Rows and columns
df.shape

(558837, 16)

In [5]:
df.columns

Index(['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state',
       'condition', 'odometer', 'color', 'interior', 'seller', 'mmr',
       'sellingprice', 'saledate'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  str
 2   model         548438 non-null  str
 3   trim          548186 non-null  str
 4   body          545642 non-null  str
 5   transmission  493485 non-null  str
 6   vin           558833 non-null  str
 7   state         558837 non-null  str
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  str
 11  interior      558088 non-null  str
 12  seller        558837 non-null  str
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  str
dtypes: float64(4), int64(1), str(11)
memory usage: 68.2 MB

In [7]:
df.describe()

,year,condition,odometer,mmr,sellingprice
count,558837.000000,547017.000000,558743.000000,558799.000000,558825.000000
mean,2010.038927,30.672365,68320.017767,13769.377495,13611.358810
std,3.966864,13.402832,53398.542821,9679.967174,9749.501628
min,1982.000000,1.000000,1.000000,25.000000,1.000000
25%,2007.000000,23.000000,28371.000000,7100.000000,6900.000000
50%,2012.000000,35.000000,52254.000000,12250.000000,12100.000000
75%,2013.000000,42.000000,99109.000000,18300.000000,18200.000000
max,2015.000000,49.000000,999999.000000,182000.000000,230000.000000

In [8]:
df.isnull().sum()

year                0
make            10301
model           10399
trim            10651
body            13195
transmission    65352
vin                 4
state               0
condition       11820
odometer           94
color             749
interior          749
seller              0
mmr                38
sellingprice       12
saledate           12
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df_clean = df.copy()

In [11]:
df_clean = df_clean.dropna(subset=['sellingprice', 'saledate'])

In [12]:
df_clean = df_clean.drop(columns=['vin'])

In [37]:
# Fill numerical columns properly
df_clean['condition'] = df_clean['condition'].fillna(df_clean['condition'].median())

df_clean['odometer'] = df_clean['odometer'].fillna(df_clean['odometer'].median())

df_clean['mmr'] = df_clean['mmr'].fillna(df_clean['mmr'].median())

In [38]:
cols = ['make', 'model', 'trim', 'body', 'transmission', 'color', 'interior']

df_clean[cols] = df_clean[cols].fillna('Unknown')

In [39]:
df_clean['saledate'] = pd.to_datetime(df_clean['saledate'], errors='coerce', utc=True)

In [40]:
df_clean['saledate'].head()

0   2014-12-16 04:30:00+00:00
1   2014-12-16 04:30:00+00:00
2   2015-01-14 20:30:00+00:00
3   2015-01-28 20:30:00+00:00
4   2014-12-18 04:30:00+00:00
Name: saledate, dtype: datetime64[us, UTC]

In [41]:
df_clean['saledate'].isnull().sum()

np.int64(0)

In [42]:
df_clean = df_clean.dropna(subset=['saledate'])

In [43]:
df_clean.isnull().sum()

year            0
make            0
model           0
trim            0
body            0
transmission    0
state           0
condition       0
odometer        0
color           0
interior        0
seller          0
mmr             0
sellingprice    0
saledate        0
dtype: int64

In [44]:
df_clean.shape

(558804, 15)

In [45]:
df_clean.to_csv("../data/processed/clean_data.csv", index=False)